export const DYNAMODB_OPTIONS = {};
export const LOCAL_DYNAMODB_OPTIONS = {
  region: 'localhost',
  endpoint: process.env.LOCAL_DYNAMO_ENPOINT,
};

export const DYNAMODB_CONNECTION_TABLE = process.env.DYNAMODB_CONNECTION_TABLE;
export const DYNAMODB_CONNECTION_TABLE_PARTITION_KEY =
  process.env.DYNAMODB_CONNECTION_TABLE_PARTITION_KEY;

export const DYNAMODB_CONNECTION_TABLE_USER_GSI =
  process.env.DYNAMODB_CONNECTION_TABLE_USER_GSI;
export const DYNAMODB_CONNECTION_TABLE_USER_GSI_PARTITION_KEY =
  process.env.DYNAMODB_CONNECTION_TABLE_USER_GSI_PARTITION_KEY;

export const DYNAMODB_CHAT_TABLE = process.env.DYNAMODB_CHAT_TABLE;
export const DYNAMODB_CHAT_TABLE_PARTITION_KEY =
  process.env.DYNAMODB_CHAT_TABLE_PARTITION_KEY;
export const DYNAMODB_CHAT_TABLE_SORT_KEY =
  process.env.DYNAMODB_CHAT_TABLE_SORT_KEY;

export const DYNAMODB_CHAT_TABLE_KEY_UPDATED_GSI =
  process.env.DYNAMODB_CHAT_TABLE_KEY_UPDATED_GSI;
export const DYNAMODB_CHAT_TABLE_KEY_UPDATED_GSI_PARTITION_KEY =
  process.env.DYNAMODB_CHAT_TABLE_KEY_UPDATED_GSI_PARTITION_KEY;
export const DYNAMODB_CHAT_TABLE_KEY_UPDATED_GSI_SORT_KEY =
  process.env.DYNAMODB_CHAT_TABLE_KEY_UPDATED_GSI_SORT_KEY;
